source 'https://github.com/slb2709673/SlbSpces.git'
#use_frameworks!
use_modular_headers!

platform :ios, '8.0'

target 'testswiftoc_Example' do
  pod 'testswiftoc', :path => '../'

  target 'testswiftoc_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase'
  end
end
